# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shu # ex. I m Chuan
name: 舒 # ex. DONGChuan
email: 864963368@qq.com
wx: s864963368
location: 湖北武汉 # ex. Nice, France
company: Good Good Study
company_url: undefined
github_url: https://github.com/SeeTheDream # ex. https://github.com/DONGChuan
github_username: SeeTheDream # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: SeeTheDream/SeeTheDream.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: http://localhost:4000
url: http://SeeTheDream.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 主页

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: 博客

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


categories: [NodeJS, JavaScript, Java, CSS, HTML]

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, MongoDB, Redis, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
